import images from './images';

export const works = [
  {
    id: 1,
    title: 'Azul',
    description: '300x300, plaster',
    img: images.azul,
    tag: 'Available',
  },
  {
    id: 2,
    title: 'Cotton Field',
    description: '300x300, plaster',
    img: images.cotton_field,
    tag: 'Available',
  },
  {
    id: 3,
    title: 'Everglades Sunrise',
    description: '300x300, plaster',
    img: images.everglades_sunrise,
    tag: 'Available',
  },
  {
    id: 4,
    title: 'The Yellow Umbrella',
    description: '300x300, plaster',
    img: images.the_yellow_umbrella,
    tag: 'Available',
  },
  {
    id: 5,
    title: 'Beach Aerial',
    description: '300x300, plaster',
    img: images.beach_aerial,
    tag: 'Sold',
  },
  {
    id: 6,
    title: 'Citrus by the Sea',
    description: '300x300, plaster',
    img: images.citrus_by_the_sea,
    tag: 'Sold',
  },
  {
    id: 7,
    title: 'Fish Fossil',
    description: '300x300, plaster',
    img: images.fish_fossil,
    tag: 'Sold',
  },
  {
    id: 8,
    title: 'Night Swimming',
    description: '300x300, plaster',
    img: images.night_swimming,
    tag: 'Sold',
  },
  {
    id: 9,
    title: 'Sea Turtle in White',
    description: '300x300, plaster',
    img: images.sea_turtle_in_white,
    tag: 'Sold',
  },
  {
    id: 10,
    title: 'Tropicale',
    description: '300x300, plaster',
    img: images.tropicale,
    tag: 'Sold',
  },
  {
    id: 11,
    title: 'Water Lillies',
    description: '300x300, plaster',
    img: images.water_lillies,
    tag: 'Sold',
  },
  {
    id: 12,
    title: 'Western Lake',
    description: '300x300, plaster',
    img: images.western_lake,
    tag: 'Sold',
  },
];
